### ISSUE TITLE
Support autoloading bundlers

### ISSUE THREAD

**Issue by noverby** [accelbread/flakelight#3]
It would make sense to implement autoloading for bundlers, since they are integrated into Nix

**Comment by accelbread** [comment]
Hey, sorry for the delay; taking a look.

Unfortunately, that PR won't work as the option needs to be implemented before the auto-import code can set it.

Will push code to enable bundlers shortly.

**Comment by accelbread** [comment]
Fixed in d7c7f4634a7f0ddb2a85e1f27f965fcc8caf9092.
